on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job1
        run: echo "Hi, Sky this side"

  job2:
    runs-on : ubuntu-latest
    needs : job1 # for dependent jobs
    steps : 
      - name: Job2
        run : echo " I am here to learn github actions"
  
